/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/cuda/amp/grad_scaler.py:120: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
  0%|                                                                                                                                                   | 0/1334 [00:00<?, ?it/s]/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/amp/autocast_mode.py:204: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
  0%|                                                                                                                                                   | 0/1334 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/Users/mohamedmafaz/Desktop/CycleGAN/train.py", line 186, in <module>
    main("160fb2b5d5c5791978cce34bd4d7cf472ef06847", "CycleGAN")
  File "/Users/mohamedmafaz/Desktop/CycleGAN/train.py", line 163, in main
    train(
  File "/Users/mohamedmafaz/Desktop/CycleGAN/train.py", line 90, in train
    "Generated A Images": [wandb.Image(f"saved_images_A_{epoch}.png", caption=f"Epoch {epoch} - A Generated")],
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/data_types/image.py", line 178, in __init__
    self._initialize_from_path(data_or_path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/data_types/image.py", line 276, in _initialize_from_path
    self._set_file(path, is_tmp=False)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/data_types/base_types/media.py", line 65, in _set_file
    with open(self._path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'saved_images_A_0.png'
